In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('score_updated.csv', encoding = 'latin-1')
df.head()

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [8]:
x = df.drop('Scores', axis=1)
y=df['Scores']
x.head()

   Hours
0    2.5
1    5.1
2    3.2
3    8.5
4    3.5

In [9]:
x.shape

(96, 1)

In [10]:
y.shape

(96,)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=5, test_size=0.2)

In [12]:
x_train.shape

(76, 1)

In [13]:
y_train.shape

(76,)

In [14]:
x_test.shape

(20, 1)

In [15]:
y_test.shape

(20,)