In [ ]:
# this ordinal encoder is used to change catagorical data into numerical data, which is required for machine learning models to process the data effectively. The encoder assigns a unique integer to each category in the dataset, allowing the model to understand and learn from the categorical features. This is particularly useful when dealing with features that have a natural order or hierarchy, as it preserves the ordinal relationship between categories.

In [2]:
import pandas as pd

d = {'sales': [100, 200, 300, 400, 500],
     'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
     'size': ['small', 'medium', 'large', 'medium', 'small']
     }

df=pd.DataFrame(data=d)
df.head()

   sales         city    size
0    100     New York   small
1    200  Los Angeles  medium
2    300      Chicago   large
3    400      Houston  medium
4    500      Phoenix   small

In [9]:
from sklearn.preprocessing import OrdinalEncoder
encoder= OrdinalEncoder(categories=[df['size'].unique()])
df['new_size']=encoder.fit_transform(df[['size']])
df.head()

   sales         city    size  new_size
0    100     New York   small       0.0
1    200  Los Angeles  medium       1.0
2    300      Chicago   large       2.0
3    400      Houston  medium       1.0
4    500      Phoenix   small       0.0